apiVersion: v1
kind: Service
metadata:
  name: green-app-service
  labels:
    app: green-app
    ingress-color: green
spec:
  type: NodePort
  selector:
    app: green-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081